CREATE TABLE users(

id INTEGER PRIMARY KEY AUTOINCREMENT,

username TEXT UNIQUE,

email TEXT UNIQUE,

password TEXT

);

CREATE TABLE summaries(

id INTEGER PRIMARY KEY AUTOINCREMENT,

filename TEXT,

summary TEXT,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);