import os
import re
from datetime import datetime
from config import Config


def _sanitize_text(text):
    """Remove non-latin1 characters for FPDF compatibility."""
    if not text:
        return ""
    return text.encode('latin-1', errors='replace').decode('latin-1')


def generate_summary_pdf(summary_record, export_path=None):
    """
    Generate a PDF file for a single summary record.

    Args:
        summary_record (dict): Dictionary with keys:
            id, filename, summary, keywords, created_at, username
        export_path (str): Optional full path for the output PDF.

    Returns:
        str: The path to the generated PDF file.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError(
            "fpdf2 is required for PDF export. "
            "Install it with: pip install fpdf2"
        )

    class SummaryPDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 14)
            self.set_text_color(33, 150, 243)
            self.cell(0, 10, 'Smart Notes Summarizer', align='C', ln=True)
            self.set_draw_color(33, 150, 243)
            self.set_line_width(0.5)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, f'Page {self.page_no()} | Generated by Smart Notes Summarizer', align='C')

    pdf = SummaryPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title section
    pdf.set_font('Arial', 'B', 16)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, 'Summary Report', ln=True)
    pdf.ln(2)

    # Metadata
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(100, 100, 100)
    filename = _sanitize_text(summary_record.get('filename', 'Unknown'))
    created_at = summary_record.get('created_at', '')
    username = _sanitize_text(summary_record.get('username', 'Unknown'))

    if isinstance(created_at, str):
        created_display = created_at
    else:
        created_display = created_at.strftime('%B %d, %Y %H:%M') if created_at else 'Unknown'

    pdf.cell(0, 6, f'File: {filename}', ln=True)
    pdf.cell(0, 6, f'Generated by: {username}', ln=True)
    pdf.cell(0, 6, f'Date: {created_display}', ln=True)
    pdf.ln(4)

    # Divider
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Summary section
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(33, 150, 243)
    pdf.cell(0, 8, 'Summary', ln=True)
    pdf.ln(2)

    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(40, 40, 40)
    summary_text = _sanitize_text(summary_record.get('summary', 'No summary available.'))
    pdf.multi_cell(0, 6, summary_text)
    pdf.ln(6)

    # Keywords section
    keywords = summary_record.get('keywords', '')
    if keywords:
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        pdf.set_font('Arial', 'B', 12)
        pdf.set_text_color(33, 150, 243)
        pdf.cell(0, 8, 'Keywords', ln=True)
        pdf.ln(2)

        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(60, 60, 60)
        keywords_text = _sanitize_text(keywords)
        pdf.multi_cell(0, 6, keywords_text)

    # Determine output path
    if not export_path:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_filename = re.sub(r'[^\w\-_.]', '_', filename)
        pdf_filename = f"summary_{safe_filename}_{timestamp}.pdf"
        export_path = os.path.join(Config.EXPORT_FOLDER, pdf_filename)

    os.makedirs(os.path.dirname(export_path), exist_ok=True)
    pdf.output(export_path)
    return export_path


def generate_all_summaries_pdf(summaries, username, export_path=None):
    """
    Generate a PDF containing all summaries for a user (dashboard export).

    Args:
        summaries (list): List of summary dicts.
        username (str): The user's username.
        export_path (str): Optional output path.

    Returns:
        str: Path to the generated PDF.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError(
            "fpdf2 is required for PDF export. "
            "Install it with: pip install fpdf2"
        )

    class AllSummariesPDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 13)
            self.set_text_color(33, 150, 243)
            self.cell(0, 10, 'Smart Notes Summarizer - Summary History', align='C', ln=True)
            self.set_draw_color(33, 150, 243)
            self.set_line_width(0.5)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, f'Page {self.page_no()} | Smart Notes Summarizer', align='C')

    pdf = AllSummariesPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Report header
    pdf.set_font('Arial', 'B', 15)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, f"Summary Report for {_sanitize_text(username)}", ln=True)

    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(120, 120, 120)
    now_str = datetime.now().strftime('%B %d, %Y %H:%M')
    pdf.cell(0, 6, f"Generated on: {now_str}", ln=True)
    pdf.cell(0, 6, f"Total summaries: {len(summaries)}", ln=True)
    pdf.ln(4)

    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    for idx, record in enumerate(summaries, start=1):
        # Entry header
        pdf.set_font('Arial', 'B', 11)
        pdf.set_text_color(33, 150, 243)
        filename = _sanitize_text(record.get('filename', 'Unknown'))
        pdf.cell(0, 8, f"{idx}. {filename}", ln=True)

        # Date
        pdf.set_font('Arial', 'I', 9)
        pdf.set_text_color(130, 130, 130)
        created_at = record.get('created_at', '')
        pdf.cell(0, 5, f"Date: {created_at}", ln=True)
        pdf.ln(2)

        # Summary text
        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(50, 50, 50)
        summary_text = _sanitize_text(record.get('summary', 'No summary.'))
        pdf.multi_cell(0, 5, summary_text)
        pdf.ln(2)

        # Keywords
        keywords = record.get('keywords', '')
        if keywords:
            pdf.set_font('Arial', 'B', 9)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(0, 5, f"Keywords: {_sanitize_text(keywords)}", ln=True)

        pdf.ln(4)
        pdf.set_draw_color(220, 220, 220)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

    # Determine output path
    if not export_path:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_user = re.sub(r'[^\w\-_]', '_', username)
        pdf_filename = f"all_summaries_{safe_user}_{timestamp}.pdf"
        export_path = os.path.join(Config.EXPORT_FOLDER, pdf_filename)

    os.makedirs(os.path.dirname(export_path), exist_ok=True)
    pdf.output(export_path)
    return export_path